// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybdyjelodvaudvdbobks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZHlqZWxvZHZhdWR2ZGJvYmtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc5MjA0OTIsImV4cCI6MjA5MzQ5NjQ5Mn0.RP2VY_NQNXOz9YuNPCgjQ11lyYr2vXOjSMiUSYgiBhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});